name: Run DBT on Databricks

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      dbt_target:
        description: 'Specify the DBT target (e.g., dev, stage)'
        required: true
        default: stage
  push: # Runs on push to specific branches
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    env:
      DBT_TARGET: ${{ inputs.dbt_target }}
      
    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3-1: Install DBT-core
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core

    # Step 3-2: Install DBT and Databricks Adapter
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-databricks
        
    # Step 4: Configure DBT profiles.yml
    - name: Set up DBT profile
      run: |
        mkdir -p ~/.dbt
        echo "
        databricks_profile:
          outputs:
            dev:
              type: databricks
              server_host: ${{ secrets.DATABRICKS_SERVER_HOST }}
              http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
              token: ${{ secrets.DATABRICKS_TOKEN }}
              schema: ${{ secrets.DBT_SCHEMA || 'default' }}
              catalog: ${{ secrets.DBT_CATALOG || 'hive_metastore' }}
          target: dev
        " > ~/.dbt/profiles.yml

    # Step 5: Debug connection 
    - name: Test connection
      run: dbt debug --target ${{ env.DBT_TARGET }}

    # Step 6: Install dependencies (dbt deps)
    - name: Install DBT dependencies
      run: dbt deps --target ${{ env.DBT_TARGET }}

    # Step 7: Run DBT models
    - name: Run DBT models
      run: dbt run --target ${{ env.DBT_TARGET }}
